### ISSUE TITLE
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

### ISSUE THREAD

**Issue by Wolfware2023** [jsakamoto/Toolbelt.Blazor.FileDropZone#4]
I found a new error int our log with this library:

```
Unhandled exception in circuit '"AXOSeY-MfXHMG7kocl7Xzql_DEwyYOURt6HSlUIy5kU"'.
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
   at Toolbelt.Blazor.FileDropZone.FileDropZone.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Additional info:
We use the FileDropZone in a component used 4 times in one view. Mostly this works as expected. Just this error occurred once for one user so far.

We are currently still using .Net 6 and Blazor Server. 
The app is hosted via IIS. The client browser I don't know. Likely Microsoft Edge.
Sadly the project is company property and cannot be shared.

**Comment by jsakamoto** [comment]
Hi @Wolfware2023,

I handled this issue and published the new version, v.3.0.1.

- https://www.nuget.org/packages/Toolbelt.Blazor.FileDropZone/3.0.1#releasenotes-body-tab

Could you try it out?
Thank you for your contributions.
